# Generated by Django 4.1.5 on 2025-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0034_jsonobjectenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampledocument',
            name='document_path',
            field=models.CharField(blank=True, help_text='Path to the document within the doctools/media directory, e.g., "examples/json/beams.json".', max_length=300),
        ),
        migrations.AlterField(
            model_name='exampledocument',
            name='document',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jsonobject',
            name='object_type',
            field=models.SmallIntegerField(choices=[(1, 'Dictionary'), (7, 'Dictionary with user-defined keys'), (2, 'Array'), (3, 'String'), (4, 'Number'), (5, 'Boolean'), (6, 'Literal string')]),
        ),
    ]
