# Generated by Django 4.1.5 on 2025-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0035_exampledocument_document_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonobject',
            name='uses_global_attrs',
            field=models.BooleanField(default=True),
        ),
    ]
