# Generated by Django 4.1.5 on 2026-02-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0036_jsonobject_uses_global_attrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlschema',
            name='version',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='union_types',
            field=models.ManyToManyField(blank=True, help_text='If this data type is a union of multiple other types, list them here.', to='spectools.datatype'),
        ),
    ]
