# Generated by Django 4.1.5 on 2026-02-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0037_xmlschema_version_alter_datatype_union_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonobject',
            name='regex',
            field=models.CharField(blank=True, help_text='For strings, an optional regex to use for this value. Make sure to use ^ at the start and $ at the end.', max_length=255),
        ),
    ]
